// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_AVA_Proiect.Data;

namespace Web_AVA_Proiect.Migrations
{
    [DbContext(typeof(Web_AVA_ProiectContext))]
    [Migration("20220106144219_Sala")]
    partial class Sala
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web_AVA_Proiect.Models.Angajat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nr_telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salariu")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Masaj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Denumire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Masaj");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.MasajCategorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MasajID")
                        .HasColumnType("int");

                    b.Property<int>("ProgramareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MasajID");

                    b.HasIndex("ProgramareID");

                    b.ToTable("MasajCategorie");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AngajatID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ora_Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AngajatID");

                    b.HasIndex("SalaID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Etaj")
                        .HasColumnType("int");

                    b.Property<int>("Numar")
                        .HasColumnType("int");

                    b.Property<string>("Strada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.MasajCategorie", b =>
                {
                    b.HasOne("Web_AVA_Proiect.Models.Masaj", "Masaj")
                        .WithMany("Masaje")
                        .HasForeignKey("MasajID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_AVA_Proiect.Models.Programare", "Programare")
                        .WithMany("MasajCategorii")
                        .HasForeignKey("ProgramareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masaj");

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Programare", b =>
                {
                    b.HasOne("Web_AVA_Proiect.Models.Angajat", "Angajat")
                        .WithMany("Programari")
                        .HasForeignKey("AngajatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_AVA_Proiect.Models.Sala", "Sala")
                        .WithMany("Programari")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Angajat");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Angajat", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Masaj", b =>
                {
                    b.Navigation("Masaje");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Programare", b =>
                {
                    b.Navigation("MasajCategorii");
                });

            modelBuilder.Entity("Web_AVA_Proiect.Models.Sala", b =>
                {
                    b.Navigation("Programari");
                });
#pragma warning restore 612, 618
        }
    }
}
